[help]
url = "https://github.com/ores-otel/ores-otel-api-server.rs"

[parse]
allow_unknown = false

[env]
load = false

[flags.bind]
env = "ORES_OTEL_API_BIND"
aliases = ["bind"]
type = "string"
default = "127.0.0.1:8080"
help = "HTTP bind address."

[flags.tcp-bind]
env = "ORES_OTEL_API_TCP_BIND"
aliases = ["tcp-bind"]
type = "string"
help = "Optional stateful TCP bind address."

[flags.nats-url]
env = "ORES_OTEL_NATS_URL"
aliases = ["nats-url"]
type = "string"
help = "Optional NATS URL."
